const Map<String, String> ar = {
  "Title": "العنوان",
  "Price": "السعر",
  "expDate": "تاريخ انتهاء الصلاحية",
  "Product list": "عرض المنتجات",
  "Settings": "الاعدادات",
  "My Products": "منتجاتي",
  "Language": "اللغة",
  "Contact Us": "تواصل معنا",
  "Log Out": "تسحيل الخروج",
  "Title or Author Name": "بحث ..",
  "Name": "الاسم",
  "Email": "الإيميل ",
  "Image URL": "رابط الصورة",
  "Category": "الفئة",
  "Expiration Date": "تاريخ انتهاء الصلاحية",
  "Phone Number": "رقم الهاتف",
  "Quantity": "الكمية",
  "Common Info": "معلومات اضافية",
  "Add": "اضافة",
  "Continue": "استمرار",
  "OR": "او",
  "Does not have account?": "ليس لديك حساب ؟",
  "Fruit": "فواكه",
  "Juice": "عصائر",
  "Snacks": "سناك",
  "sandwich": "سندويش",
  "Sign Up": "تسحيل حساب ",
  "Login": "تسجيل الدخول",
  "product details": "معلومات المنتج",
  "Phone :  +963 988 550 610": "رقم الهاتف: 0988550610",
  "Candy": "حلويات",
  "Price after Discount": "السعر بعد التخفيضات",
  "second Discount example :50%": "الخصم الثاني %",
  "first Discount example :30%": "الخصم الاول %",
  "third Discount": "الخصم الثالث %",
  "Add Products": "إضافة منتج",
};
