const Map<String, String> en = {
  "Title": "Title",
  "Price": "Price",
  "expDate": "Expiration Date",
  "Product list": "Product list",
  "Settings": "Settings",
  "My Products": "My Products",
  "Language": "Language",
  "Contact Us": "Contact Us",
  "Log Out": "Log Out",
  "Login": "Login",
  "Title or Author Name": "Title or Author Name",
  "Name": "Name",
  "Email": "Email",
  "Image URL": "Image URL",
  "Category": "Category",
  "Expiration Date": "Expiration Date",
  "Phone Number": "Phone Number",
  "Quantity": "Quantity",
  "Common Info": "Common Info",
  "Add": "Add",
  "Continue": "Continue",
  "OR": "OR",
  "Does not have account?": "Does not have account?",
  "Fruit": "Fruit",
  "Juice": "Juice",
  "Snacks": "Snacks",
  "sandwich": "sandwich",
  "Sign Up": "Sign Up",
  "product details": "product details",
  "Phone :  +963 988 550 610": "Phone :  +963 988 550 610",
  "Candy": "Candy",
  "Price after Discount": "Price after Discount",
  "second Discount example :50%": "second Discount example :50%",
  "third Discount": "third Discount",
  "first Discount example :30%": "first Discount example :30%",
  "Add Products": "Add Products",
};
